### PR TITLE
Use that.constructor.name as fallback

### PR DESCRIPTION
**Pull request by f0rr0**

### CODE REVIEW

**Comment by f0rr0** [comment]
@jondot please review and merge/release if you find it correct. `displayName` returns `undefined` all the time, so identifying classes is hard in the console.

**Comment by jondot** [comment]
Nice catch! Thanks!

**Comment by f0rr0** [comment]
@jondot it'll be great if you release on npm

**Comment by jondot** [comment]
done!

**Comment by f0rr0** [comment]
@jondot is this bundled in the app in release mode?

**Comment by jondot** [comment]
Right now it's under a flag, so it's bundled, but not active, see https://github.com/jondot/react-native-slowlog/blob/master/index.js#L11

**Pull request merged**
